server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/fifth
    username: DBAdmin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

fifth:
  baseUri: http://localhost:8080