// Generated by delombok at Sat Sep 17 17:47:34 PDT 2022
package com.quintrix.jepsen.erik.fifth.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "departments")
public class Department {
  private String deptName;
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "dept_id")
  private Integer deptNumber;

  @java.lang.SuppressWarnings("all")
  public String getDeptName() {
    return this.deptName;
  }

  @java.lang.SuppressWarnings("all")
  public Integer getDeptNumber() {
    return this.deptNumber;
  }

  @java.lang.SuppressWarnings("all")
  public void setDeptName(final String deptName) {
    this.deptName = deptName;
  }

  @java.lang.SuppressWarnings("all")
  public void setDeptNumber(final Integer deptNumber) {
    this.deptNumber = deptNumber;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this)
      return true;
    if (!(o instanceof Department))
      return false;
    final Department other = (Department) o;
    if (!other.canEqual((java.lang.Object) this))
      return false;
    final java.lang.Object this$deptNumber = this.getDeptNumber();
    final java.lang.Object other$deptNumber = other.getDeptNumber();
    if (this$deptNumber == null ? other$deptNumber != null
        : !this$deptNumber.equals(other$deptNumber))
      return false;
    final java.lang.Object this$deptName = this.getDeptName();
    final java.lang.Object other$deptName = other.getDeptName();
    if (this$deptName == null ? other$deptName != null : !this$deptName.equals(other$deptName))
      return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof Department;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $deptNumber = this.getDeptNumber();
    result = result * PRIME + ($deptNumber == null ? 43 : $deptNumber.hashCode());
    final java.lang.Object $deptName = this.getDeptName();
    result = result * PRIME + ($deptName == null ? 43 : $deptName.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "Department(deptName=" + this.getDeptName() + ", deptNumber=" + this.getDeptNumber()
        + ")";
  }

  @java.lang.SuppressWarnings("all")
  public Department() {}

  @java.lang.SuppressWarnings("all")
  public Department(final String deptName, final Integer deptNumber) {
    this.deptName = deptName;
    this.deptNumber = deptNumber;
  }
}
