// Generated by delombok at Sat Sep 17 17:47:34 PDT 2022
package com.quintrix.jepsen.erik.fifth.model;

import javax.persistence.Entity;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(name = "persons")
public class Person {
  private String fName;
  private String lName;
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Integer personId;
  @ManyToOne
  @JoinColumn(name = "dept_id", foreignKey = @ForeignKey(name = "FK_departments"))
  private Department dept;

  @java.lang.SuppressWarnings("all")
  public Person() {}

  @java.lang.SuppressWarnings("all")
  public Person(final String fName, final String lName, final Integer personId,
      final Department dept) {
    this.fName = fName;
    this.lName = lName;
    this.personId = personId;
    this.dept = dept;
  }

  @java.lang.SuppressWarnings("all")
  public String getFName() {
    return this.fName;
  }

  @java.lang.SuppressWarnings("all")
  public String getLName() {
    return this.lName;
  }

  @java.lang.SuppressWarnings("all")
  public Integer getPersonId() {
    return this.personId;
  }

  @java.lang.SuppressWarnings("all")
  public Department getDept() {
    return this.dept;
  }

  @java.lang.SuppressWarnings("all")
  public void setFName(final String fName) {
    this.fName = fName;
  }

  @java.lang.SuppressWarnings("all")
  public void setLName(final String lName) {
    this.lName = lName;
  }

  @java.lang.SuppressWarnings("all")
  public void setPersonId(final Integer personId) {
    this.personId = personId;
  }

  @java.lang.SuppressWarnings("all")
  public void setDept(final Department dept) {
    this.dept = dept;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this)
      return true;
    if (!(o instanceof Person))
      return false;
    final Person other = (Person) o;
    if (!other.canEqual((java.lang.Object) this))
      return false;
    final java.lang.Object this$personId = this.getPersonId();
    final java.lang.Object other$personId = other.getPersonId();
    if (this$personId == null ? other$personId != null : !this$personId.equals(other$personId))
      return false;
    final java.lang.Object this$fName = this.getFName();
    final java.lang.Object other$fName = other.getFName();
    if (this$fName == null ? other$fName != null : !this$fName.equals(other$fName))
      return false;
    final java.lang.Object this$lName = this.getLName();
    final java.lang.Object other$lName = other.getLName();
    if (this$lName == null ? other$lName != null : !this$lName.equals(other$lName))
      return false;
    final java.lang.Object this$dept = this.getDept();
    final java.lang.Object other$dept = other.getDept();
    if (this$dept == null ? other$dept != null : !this$dept.equals(other$dept))
      return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof Person;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $personId = this.getPersonId();
    result = result * PRIME + ($personId == null ? 43 : $personId.hashCode());
    final java.lang.Object $fName = this.getFName();
    result = result * PRIME + ($fName == null ? 43 : $fName.hashCode());
    final java.lang.Object $lName = this.getLName();
    result = result * PRIME + ($lName == null ? 43 : $lName.hashCode());
    final java.lang.Object $dept = this.getDept();
    result = result * PRIME + ($dept == null ? 43 : $dept.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "Person(fName=" + this.getFName() + ", lName=" + this.getLName() + ", personId="
        + this.getPersonId() + ", dept=" + this.getDept() + ")";
  }
}
